"""Core project classes: entities and interfaces."""

from roll.core.entities import (
    Attendance,
    AttendanceShema,
    AttendanceStatus,
    AttendanceUpdateDTO,
    BaseAttendance,
    BaseEvent,
    BaseEventTemplate,
    BaseIdentifier,
    BasePerson,
    CardIdentifier,
    Event,
    EventShema,
    EventTemplate,
    EventTemplateShema,
    EventTemplateUpdateDTO,
    EventUpdateDTO,
    IdentifierShema,
    IdentifierType,
    IdentifierUpdateDTO,
    Person,
    PersonShema,
    PersonUpdateDTO,
    QRIdentifier,
)
from roll.core.init_database import init_database
from roll.core.interfaces.repositories import (
    IAttendanceRepository,
    IEventRepository,
    IEventTemplateRepository,
    IIdentifierRepository,
    IPersonRepository,
)
from roll.core.interfaces.services import (
    IAttendanceService,
    ICameraAvailabilityService,
    IEventService,
    IEventTemplateService,
    IIdentifierReaderService,
    IIdentifierService,
    IPersonService,
    IVerificationService,
)
from roll.core.setup_logging import setup_logging

__all__ = [
    "Attendance",
    "AttendanceShema",
    "AttendanceStatus",
    "AttendanceUpdateDTO",
    "BaseAttendance",
    "BaseEvent",
    "BaseEventTemplate",
    "BaseIdentifier",
    "BasePerson",
    "CardIdentifier",
    "Event",
    "EventShema",
    "EventTemplate",
    "EventTemplateShema",
    "EventTemplateUpdateDTO",
    "EventUpdateDTO",
    "IAttendanceRepository",
    "IAttendanceService",
    "ICameraAvailabilityService",
    "IEventRepository",
    "IEventService",
    "IEventTemplateRepository",
    "IEventTemplateService",
    "IIdentifierReaderService",
    "IIdentifierRepository",
    "IIdentifierService",
    "IPersonRepository",
    "IPersonService",
    "IVerificationService",
    "IdentifierShema",
    "IdentifierType",
    "IdentifierUpdateDTO",
    "Person",
    "PersonShema",
    "PersonUpdateDTO",
    "QRIdentifier",
    "init_database",
    "setup_logging",
]
